version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER} # Replace with your desired username
      POSTGRES_PASSWORD: ${DB_PASSWORD} # Replace with your desired password
      POSTGRES_DB: ${DB_NAME} # Replace with your desired database name
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persists data between container restarts

volumes:
  postgres_data: